# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'GameHub iOS' do

pod 'RestKit', '~> 0.24'
pod 'NSRails', 		'~> 2.2'


end

target 'GameHub iOSTests' do

end

