# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'GameHub iOS' do

pod 'RestKit', '~> 0.24'
pod 'NSRails', 		'~> 2.2'
pod 'MMDrawerController', '~> 0.5.7'


end

target 'GameHub iOSTests' do

pod 'OCMock', '~> 3.1.2'

end

